### ISSUE TITLE
Nodes with more than 200 children are slow

### ISSUE THREAD

**Issue by zevero** [wix/angular-tree-control#10]
I have a tree with 65000 entries, which is way too large for the "average treeview".

Angular-tree-control however is still  snappy - as long es a node do not have too many children:
On latest chrome and good hardware it starts to get sluggish with more than 100 entries and slow with more than 200. Sadly I have some nodes with 1000 children, which brings the browser tab to halt.

Tracking it down with Profiler, it has something to do with eventHandlers, which led me to the idea to try this
http://www.bennadel.com/blog/2448-Using-jQuery-Event-Delegation-In-AngularJS.htm
approach (despite of the jquery dependancy).
This and reducing the template doubled performance! But this is still not enough.

I was trying to dynamically add and remove the treedata, but it doesnt change the problem, that there are up to 1000 children in one folder.

Maybe one could get rid of the attached function nodeExpanded() on treeview element, but I didnt manage to do that ...

**Comment by yoavaa** [comment]
fixed
