### ISSUE TITLE
Support for Changing Node Names

### ISSUE THREAD

**Issue by buchgeher** [wix/angular-tree-control#100]
Hi,

I'm trying to reflect name changes of tree nodes. Simply changing the tree model (as it is the case for dynamically adding and removing nodes) does not do the trick. Is there any API/best practice for such functionality, e.g., updating/reloading the UI of a single node? 

Best Regards,
Georg

**Comment by yoavaa** [comment]
Can you share an example? I am not sure I understand...

**Comment by buchgeher** [comment]
I'm closing this issue because I figured it out. I wasn't aware that I have to manually update the data binding in response to background changes.
