### ISSUE TITLE
Angular's Debug Data must be enabled for scope and isolateScope to work

### ISSUE THREAD

**Issue by mike-ward** [wix/angular-tree-control#101]
The watcher for expandedNodes relies on $liElment.scope() (line 239) to return a valid value. When Angular's Debug Data is disabled (typical for production), this method returns null. This generates an exception. It also disables tree-control from responding to changes in expandedNodes.

See issue: https://github.com/angular/angular.js/issues/9515

**Comment by meffect** [comment]
Please fix this, it's a horribly bad bag

**Comment by alphilo** [comment]
Please fix this as enable debug cause the performance issue.

**Comment by yoavaa** [comment]
I am not sure how to fix this as the tree control relays on getting the scope.$id
Is there any other way to get the id of a scope without accessing the scope() method?

**Comment by benavern** [comment]
Has somebody found something working to fix this error ??? I'm experiencing the same error...
`Error: existingScope is undefined`
when debug mode is off...
thank's in advance to those who will answere :)

**Comment by yoavaa** [comment]
Guys, there is no fix to this problem save to rewrite the tree control to
use a different method of identifying nodes.
This is a big change and a breaking change, so I am not that fast to make
it.

**Comment by szabyg** [comment]
+1

**Comment by ftorghele** [comment]
+1

**Comment by tmarkley** [comment]
Has anyone been able to solve this?

**Comment by rmsint** [comment]
Just read about using a cloned `_scope` here https://github.com/a5hik/ng-sortable/pull/156/files. Maybe more a workaround, however it could prevent a rewrite and fix the error when disabling debug.

**Comment by yoavaa** [comment]
made a similar solution - hope it will be sufficient.
