### ISSUE TITLE
Using order-by on multiple fields (primary, secondary sort order)

### ISSUE THREAD

**Issue by vtirta** [wix/angular-tree-control#102]
First of all, thanks for your awesome work on angular-tree-control  :+1: 

Not sure if this is a bug or that I'm not using this correctly. I tried passing in an array of fields to sort by:
e.g. [ 'rank', 'name' ] to order-by param in order to sort the sibling nodes to be sorted with rank as primary sort predicate and name as secondary in case of a tie in rank.

But this doesn't seem to work:

```
<treecontrol class="facet-tree"
				tree-model="vm.facets"
				options="vm.treeOptions"
				selected-nodes="vm.selectedFacets"
				on-selection="vm.select(node, selected)"
				order-by="[ 'rank', 'name' ]">
```

Is there a different syntax or another way to get secondary order-by predicate to work?

**Comment by yoavaa** [comment]
what version of angular are you using?

**Comment by vtirta** [comment]
I figured out how to properly pass in the multiple fields to the order-by predicate. [rank,name] instead of using ['rank','name']. Closing the issue and thanks for your good work on the control.

**Comment by IdanCo** [comment]
This no longer seem to work. Any ideas? i tried diving into the code but i admit i don't understand this syntax from line#254:
`orderBy: $scope.orderBy ? " | orderBy:orderByFunc():isReverse()" : '',`
and how it works with the template in line#272:
`ng-repeat="node in node.{{options.nodeChildren}} | filter:filterExpression:filterComparator {{options.orderBy}}"`
the only thing that worked was to rewrite the logic of the orderBy attribute, but it looks like an overkill.

**Comment by yoavaa** [comment]
Idan, what version of angular are you using?
have you tried what @vtirta has done?

**Comment by IdanCo** [comment]
We use v1.4.5.

When i try @vtirta method, `order-by="[fieldA, fieldB]"` i get no errors, but results are not odered.
When i try `order-by="['fieldA', 'fieldB']"` i get an error `Syntax Error: Token 'fieldA' is an unexpected token at column 4 of the expression ['['fieldA', 'fieldB']']`

**Comment by vtirta** [comment]
@IdanCo I just created a PR from my fork that allows for function predicate. I thought I had requested a PR a while ago, but apparently not. Still needs to be tested w/ the current master.

https://github.com/wix/angular-tree-control/pull/208

**Comment by yoavaa** [comment]
have added support for both function and array (multi-field)
http://localhost:63342/angular.treecontrol/index.html#sorting
