### ISSUE TITLE
It doesn't work with disabled debug data

### ISSUE THREAD

**Issue by tameraydin** [wix/angular-tree-control#106]
https://code.angularjs.org/1.3.10/docs/guide/production#disabling-debug-data

In my case, everything works as expected in debug mode, but once I disable it I get this error whenever I click on an item:

TypeError: Cannot read property 'node' of undefined

**Comment by benavern** [comment]
Hi, 
Did you find a solution ? 
I'd also like to disable debug mode but cant figure out how the trees to bee displayed !
Thank's in advance !

**Comment by tameraydin** [comment]
Nope, I didn't have time to investigate it furthermore.

**Comment by tameraydin** [comment]
Apparently there is already an open issue about this #101

**Comment by yoavaa** [comment]
have a solution in place.
