### ISSUE TITLE
changing labels unexpends the tree

### ISSUE THREAD

**Issue by benavern** [wix/angular-tree-control#108]
Hello, 

I have a tree that is supposed to have that structure : 

```html
<treecontrol class="tree-light"
        tree-model="ts_data.ts_json0"
	options="treeOptions"
	on-selection="showSelected(node)">
	{{node.name}} {{node.info}}
</treecontrol>
```
node.name is always the same but node.info changes every 2 seconds. (there are bitrates and things like that)

I would like to know if it is possible to change node.info every 2 seconds without making the tree enexpending nodes when that value changes?

I tried with making the equality option return true and false ... but no success. 

Thank you in advance :)

**Comment by yoavaa** [comment]
You need to use the equality function to ignore the info change.
E.g. compare just node I'd or just node name

**Comment by benavern** [comment]
ok, 
I made that : 
```javascript
$scope.treeOptions = {
	    nodeChildren: "children",
	    dirSelectable: false,
	    equality : function(a,b){
	    	if (a === undefined || b === undefined)
				return false;
			return angular.equals(a.name, b.name);
	    }
}
```
it seems working but I don't know if it's sufisent,
could you check and tell me if this is secured and robust einough ? 
Thank you though for the help and this rapid answer !

**Comment by yoavaa** [comment]
it is sufficient, if for your application the node.name is a unique
identifier of a node. If it is possible to have multiple nodes with the
same name, you should probably add another unique identifier and compare on
it.

On Tue, Mar 3, 2015 at 12:59 PM, Benjamin CARADEUC <notifications@github.com

**Comment by benavern** [comment]
Ok, 
Thank you very much for your help.
This is sufficient for my application, Those node.name will always be the same ! :)
