### ISSUE TITLE
expandAll feature again...

### ISSUE THREAD

**Issue by benavern** [wix/angular-tree-control#109]
Hello,
I am trying to implement a expandAll function thanks to the `expanded-nodes` attribute.
I'll allways have 3 levels like so : 
```
folder (children is defined)
    |-->leafs... (children is not defined)
    |-->leafs... (children is not defined)
    |-->folder (children is defined)
    |        |-->leafs... (children is not defined)
    |        |-->leafs... (children is not defined)
```
in my controller the code is the following:
```javascript
$scope.expandedNodes = []

	$scope.openNodes = function(input_obj){
		//open the master nodes
		$scope.expandedNodes = input_obj;

		for (var i = 0; i< input_obj.length; i++){
			if (input_obj[i].children){
				for (var j = 0; j< input_obj[i].children.length; j++){
					if(input_obj[i].children[j].children){
						// open children nodes 1st level
						$scope.expandedNodes.push(input_obj[i].children[j]);
					}
				}
			}
		}

	}
```

the problem is that when I call the open all function everything becomes opened as expected but the children nodes are copied under the parent node as if everything was a parent node ...

I don't know if I am realy clear but I'm not that good in english ... :-s
 so here is a picture : 
![sans titre](https://cloud.githubusercontent.com/assets/5999900/6467553/5c009fb4-c1cf-11e4-8254-e74ac9be69f0.png)

maybe there is something more generique  ??

Please help me, it took me a long time trying many solutions but this is the only one that was nearly to work well!

Thank's in advance ! :)

**Comment by benavern** [comment]
Ok,
I ended up with something functional and I think more generic.

I have 3 trees on my page generated in an ngRepeat : 
`ng-repeat="(tsname, tsInput) in ts_data"`
for each tree I have those attributes : 
* `tree-model="tsInput"`
* `expanded-nodes="expandedNodes[$index]"` 

I have 2 buttons that open and close all nodes in each ngrepeat:
```html
<button ng-click="openNodes(tsInput, $index)">open all nodes</button>
<button ng-click="closeNodes(tsInput, $index)">close all nodes</button>
```

and in my controller I made that :

```javascript
$scope.expandedNodes = {}

$scope.openNodes = function(input_obj, index){
	var output = []

	var has_children = function (obj){
		for (var i = 0; i < obj.length; i++) {
			if(obj[i].hasOwnProperty('children')){
				output.push(obj[i]);
				has_children(obj[i].children);
			}
		};
	}

	has_children(input_obj);
	$scope.expandedNodes[index] = output;
}

$scope.closeNodes = function(input_obj, index){
	$scope.expandedNodes[index] = [];
}
```

I accept improvments, and hope that will help those that are in need such a feature.

Peace ! :+1:

**Comment by yoavaa** [comment]
In your first code snippet, you have a problem - 
in 
```
$scope.expandedNodes = []

    $scope.openNodes = function(input_obj){
        //open the master nodes
        $scope.expandedNodes = input_obj;

        for (var i = 0; i< input_obj.length; i++){
            if (input_obj[i].children){
                for (var j = 0; j< input_obj[i].children.length; j++){
                    if(input_obj[i].children[j].children){
                        // open children nodes 1st level
                        $scope.expandedNodes.push(input_obj[i].children[j]);
                    }
                }
            }
        }

    }
```

the line 
```
        $scope.expandedNodes = input_obj;
```
should have been
```
        $scope.expandedNodes.push(input_obj);
```

You second code snippet does exactly that in a more readable way (with I prefer)

**Comment by benavern** [comment]
Yes this is what I saw this morning (9:00 in france ...) but I did want to have something more **readable** and that was more robust for **reusability** if there were deeper trees one day on my application.

*I think you should write something on the README about that feature that, I think, will be asked by a ton of users.*

Thank you for your answer anyway!

**Comment by yoavaa** [comment]
The great thing about github issues is that if someone searches, he/she will find the information...

**Comment by benavern** [comment]
Yes but if that feature is something that a lot of people look for (I saw that feature request a lot of times for your application but never explained how to achieve that) its pretty good to know without going in the issues section to know if it's possible... 
However thank you for your help and feedback : -)
