### ISSUE TITLE
Limit selected nodes

### ISSUE THREAD

**Issue by norkunas** [wix/angular-tree-control#119]
Would be nice to have an option to provide how many tree items can be selected.

**Comment by dailytabs** [comment]
You should be able to do this manually by watching the selection, removing excess selections, and notifying the user. But, I agree, it would be nice to have built-in - seems like a common thing to want to limit a multi-select.

**Comment by norkunas** [comment]
Yup, I used watcher to do that, just thought that this should be in core :)
2015 liep. 20 23:55 "Daily Tabs" <notifications@github.com> rašė:
