### ISSUE TITLE
CSS relative path problem in AngularJS

### ISSUE THREAD

**Issue by yingdanh** [wix/angular-tree-control#126]
We are using angular-tree-control in our AngularJS project (generated by Yeoman full stack) with Grunt, and encounter a problem with the relative path of tree-control.css, such as:
background: url("../images/file.png") no-repeat;

It works fine in locally, while after we deployed it to our host machine, the relative path can't find the correct folder anymore. The angular-tree-control is installed under bower_components. Could you please tell us how to set Gruntfile.js to use absolute paths?

Thank  you,
Yingdan

**Comment by logstown** [comment]
+1

**Comment by yoavaa** [comment]
I have no idea. I think you will need to have a grunt task to fix the path in the css file or clone the css file and use one with the right configuration for your project
