### ISSUE TITLE
How to animate the tree expand and collapse events

### ISSUE THREAD

**Issue by codingnube** [wix/angular-tree-control#128]
Hi All,
Firstly, Kudos for giving us an awesome tree view.
I've been struggling to animate the expand and collapse events of the tree nodes.
An example of what I am trying to achieve is [Here](http://nickperkinslondon.github.io/angular-bootstrap-nav-tree/test/bs3_ng120_test_page.html).
I'm using the yeoman/generator-angular which is using AngularJS v1.3.15.
.ng-enter and .ng-leave refused to work, come what may.
After a fierce battle I managed to see some animation by using the following CSS styles:
.tree-collapsed-add{
  transition: 1s linear all;
  position: relative;
  display: block;
  opacity: 0;
  max-height: 20px;
}
.tree-collapsed-add-active{
  opacity: 1;
  max-height: 20px;
}
.tree-collapsed-remove{
  transition: 200ms linear all;
  position: relative;
  display: block;
  height: 20px;
  max-height: 20px;
  opacity: 1;
}
.tree-collapsed-remove-active{
    height: 20px;
  max-height: 20px;
  opacity: 0; 
}
The animation is jerky and not smooth at all. Any pointers will be helpful.
Thanks in advance.
CodingNube

**Comment by isaacplmann** [comment]
A full year later, but here's the css you need.  I'll make a pull request too, since this is entirely a css addition.

treeitem,
treeitem.ng-enter li,
treeitem.ng-leave li {
    transition: 200ms linear all;
}
treeitem.ng-enter li {
    position: relative;
    display: block;
    opacity: 0;
    max-height:0px;
}
treeitem.ng-enter-active li {
    opacity: 1;
    max-height:30px;
}
treeitem.ng-leave li {
    position: relative;
    display: block;
    height:30px;
    max-height: 30px;
    opacity: 1;
}
treeitem.ng-leave-active li {
    height: 0px;
    max-height:0px;
    opacity: 0;
}

**Comment by codingnube** [comment]
Awesome! Thank you Isaac. It Works!

**Comment by daniyaniazi** [comment]
what is treeitem?
