### ISSUE TITLE
Pass child scope to <treecontrol> element template content

### ISSUE THREAD

**Issue by brianfeister** [wix/angular-tree-control#129]
Given the following:

```
        <treecontrol class="tree-classic"
           tree-model="data"
           on-selection="showSelected(node)"
           selected-node="node1">
          <a ng-if="node.itemCount > 0" data-nodrag ng-click="toggle(this)" toggle-callback="this">
            <md-icon size="md" md-svg-icon="chevron-right" alt="Expand"></md-icon>
          </a>
          <md-button size="md" class="md-icon-button" ng-click="showListBottomSheet($event, this, node)">
            <md-icon size="md" md-svg-icon="dots-vertical" alt="Edit {{node.name}}"></md-icon>
          </md-button>
            {{node.name}}
        </treecontrol>
```
I would like to pass, via the click event here `<md-button size="md" class="md-icon-button" ng-click="showListBottomSheet($event, this, node)">` a reference to the childScope. I'm using Angular Material's `$bottomSheet` directive and need to pass a reference to the child scope so that I can later call `$scope.remove()` to avoid an expensive lookup to find the data deep within a tree.  Is this possible, is there an approach I'm failing to see? It seems that child scope is not something I can easily get access to in order to achieve this.

**Comment by stueynz** [comment]
Why don't you go looking for it in the set of child scopes?
Assuming you had `selectedNode="theSelectedNode"` in your tree declaration the following should help:

```javascript
for(var cs = $scope.$$childHead; cs; cs = cs.$$nextSibling) {
         if(cs.node === $scope.theSelectedNode) {
               // cs is now the child scope that matches the current selected node
         }
 }
```

**Comment by brianfeister** [comment]
Ended up going a different direction with this.
