### ISSUE TITLE
 [suggestion] Can this tree control support nodeChildren: ['children','depts'] ?

### ISSUE THREAD

**Issue by TonyLuo** [wix/angular-tree-control#134]
Can this tree control support multiple  nodeChildren to make it easier to render the tree data?

$scope.treeOptions = {
        nodeChildren: ['children','depts'],
        dirSelectable: true,
        injectClasses: {
          ul: 'a1',
          li: 'a2',
          liSelected: 'a7',
          iExpanded: 'a3',
          iCollapsed: 'a4',
          iLeaf: 'a5',
          label: 'a6',
          labelSelected: 'a8'
        }
      };

$scope.dataForTheTree =
[
    {
        "id": "Vk1WP77Q",
        "name": "SysCom A",
        "parentId": null,
        "children": [
            {
                "id": "Vk-JWPmQX",
                "name": "SysCom C",
                "parentId": "Vk1WP77Q"
            },
            {
                "id": "V1ul1-PXQm",
                "name": "SysCom A child company",
                "parentId": "Vk1WP77Q"
            }
        ],
        "depts": [
            {
                "id": "N1S1bPQXX",
                "name": "SysDept B",
                "comId": "Vk1WP77Q",
                "parentId": "NJVJWPmQX"
            },
            {
                "id": "NJVJWPmQX",
                "name": "SysDept A",
                "comId": "Vk1WP77Q",
                "parentId": null
            },
            {
                "id": "VJI1bDQXm",
                "name": "SysDept C",
                "comId": "Vk1WP77Q",
                "parentId": "NJVJWPmQX"
            }
        ]
    },
    {
        "id": "NJXybvX7m",
        "name": "SysCom E",
        "parentId": null,
        "children": [
            {
                "id": "EkilkZw7mX",
                "name": "SysCom E child company",
                "parentId": "NJXybvX7m"
            }
        ],
        "depts": []
    }
]

**Comment by yoavaa** [comment]
way to complicated to support and way to specific for a few use cases
