### ISSUE TITLE
Too much recursion (angular.equals instead of options.equality being used)

### ISSUE THREAD

**Issue by techniq** [wix/angular-tree-control#136]
My tree model (`Team`) has a circular reference parent/child properties that I believe are causing the following error:

> "Error: too much recursion
equals@http://localhost:8001/dist/scripts/vendor/angular-725456ab.js:929:1
equals@http://localhost:8001/dist/scripts/vendor/angular-725456ab.js:916:18
equals@http://localhost:8001/dist/scripts/vendor/angular-725456ab.js:931:16
equals@http://localhost:8001/dist/scripts/vendor/angular-725456ab.js:931:16
equals@http://localhost:8001/dist/scripts/vendor/angular-725456ab.js:916:18
equals@http://localhost:8001/dist/scripts/vendor/angular-725456ab.js:931:16
equals@http://localhost:8001/dist/scripts/vendor/angular-725456ab.js:931:16
equals@http://localhost:8001/dist/scripts/vendor/angular-725456ab.js:916:18
equals@http://localhost:8001/dist/scripts/vendor/angular-725456ab.js:931:16
equals@http://localhost:8001/dist/scripts/vendor/angular-725456ab.js:931:16
equals@http://localhost:8001/dist/scripts/vendor/angular-725456ab.js:916:18
equals@http://localhost:8001/dist/scripts/vendor/angular-725456ab.js:931:16
equals@http://localhost:8001/dist/scripts/vendor/angular-725456"[…]

I've attemped to add a custom equality function, and have confirmed it's being called, but I'm still receiving the error.

```js
$scope.treeControlOpts = {
    equality: function(node1, node2) {
        if (node1 === undefined || node2 === undefined)
            return false;
        return node1.id === node2.id;
    }
};
```

The think the issue might be due to `angular.equals` is still being uses within `compile`
https://github.com/wix/angular-tree-control/blob/master/angular-tree-control.js#L224-231

Should those calls be using `scope.options.equality` as well?

**Comment by yoavaa** [comment]
angular.equals is used there because we need a deep compare to validate of
the tree (the whole tree) has changed.

scope.options.equality is only used when we wanna compare a single node
without considering the node children (e.g. shallow compare).

**Comment by techniq** [comment]
@yoavaa Thanks.  I worked around my issues by prefixing my "private" properties with `$` instead of `_` so `angular.equals()` would ignore them
