### ISSUE TITLE
Need ability to set custom picture for node.

### ISSUE THREAD

**Issue by asm0dey** [wix/angular-tree-control#144]
Ehlo!

We have nodes of several types in our tree. I'm interested in setting custom picture for every type of node. Is it possible?

**Comment by yoavaa** [comment]
if you are looking to do something like a file system tree, you should use the label templates to include those images.

The pictures for the tree nodes here are like the [+] and [-] buttons you have in a file system tree, and are not instead of the file icons.

**Comment by yoavaa** [comment]
http://wix.github.io/angular-tree-control/#file-style
