### ISSUE TITLE
Designate a node as a folder or file from time is it added

### ISSUE THREAD

**Issue by Alanz2223** [wix/angular-tree-control#150]
I am creating a directory tree and I want to have a button that has two options either adding a folder or uploading a file. Is there a way to designate a node as a folder or file accordingly, so that its icon is a folder. The only way the image currently changes is if it has children.

**Comment by yoavaa** [comment]
use the isLeaf option - make the notes branches (even if they do not have children) and use on click handler to load the children
http://wix.github.io/angular-tree-control/#isleaf
