### ISSUE TITLE
Expand/collapse leaves issue

### ISSUE THREAD

**Issue by nikolay-lesko** [wix/angular-tree-control#163]
I got an issue with expand/collapse for leaves.
While expand/collapse image is hidden, the "tree-branch-head" is still visible and is clickable.
This will cause side effects, like expanding empty list of children (with custom margin for child container this will show/hide empty container with for ex 10px height), and so on.

I propose to replace 

```
<i class="tree-branch-head" ng-class="iBranchClass()" ng-click="selectNodeHead(node)"></i>
```

with 

```
<i class="tree-branch-head" ng-class="iBranchClass()" ng-hide="options.isLeaf(node)" ng-click="selectNodeHead(node)"></i>
```

in template.

This will hide this expand/collapse control, so user won't be able to do expand/collapse on leaves.

**Comment by yoavaa** [comment]
can you point me at an example of the problem? Does it happen in any of the demos in the samples page (the project site)?

**Comment by nikolay-lesko** [comment]
I'm really sorry for inconvenience.
It seems like our CSS guy have forgotten important part of your CSS, like hiding this expand/collapse element.
