### ISSUE TITLE
if config ng $interpolateProvider.startSymbol not {{ }} the template will render error

### ISSUE THREAD

**Issue by Genffy** [wix/angular-tree-control#164]
https://github.com/wix/angular-tree-control/blob/master/angular-tree-control.js#L263

why not use templatecache to render temp instead of write template in dom

**Comment by yoavaa** [comment]
we do - just a few lines above that
https://github.com/wix/angular-tree-control/blob/master/angular-tree-control.js#L258
and see the docs
http://wix.github.io/angular-tree-control/#externalTemplate

**Comment by Genffy** [comment]
Ok, thank u
