### ISSUE TITLE
Possible Issue with other directives

### ISSUE THREAD

**Issue by JPFeli** [wix/angular-tree-control#165]
I'm having a hard time debugging this.
But as for now, i'm aware of a conflict.
Here is the live demo.
http://plnkr.co/edit/cK0Pqey56slvZC7UtneZ?p=preview

This conflict is with This is Angular UI Tree.

**I think it's the constant used in both modules is the same. Constant 'treeConfig'.**
Is there any fix we can provide to avoid this conflict?

More data: treeConfig was implemented on 0.2.16.

**Comment by yoavaa** [comment]
both directive declare a treeConfig constant. But why do you need both tree directives? this seems strange by itself?

looking at the code, if you declare angular-tree-control before the angular-ui-tree everything should work except for the global template option in angular-tree-control. But I do not see angular-tree-control in the plunkr?

**Comment by pvgnd** [comment]
TreeControl does not allow drag & drop on the tree to reorganize the tree. UI-Tree does.
