### ISSUE TITLE
Adding all nodes to expanded-nodes not expanding tree

### ISSUE THREAD

**Issue by kjf77** [wix/angular-tree-control#172]
We are trying to expand the entire tree when the tree is first rendered.  We have a function to copy each node into the expandedNodes array.  Problem is that the tree is not expanding whenever we load  all nodes.  When is load one node less than all then it expands.  What could cause this?

Here is a code fragment of this:
```
$scope.allNodes = [];
    $scope.addToAllNodes = function(children) {
        if (!children || typeof (children) == "array" && children.length == 0) {
            return;
        }      
        for (var i = 0; i < children.length; i++) {
            $scope.allNodes.push(children[i]);
            $scope.addToAllNodes(children[i].children);
        }
    }

$scope.addToAllNodes($scope.dataForTheTree);
$scope.expandedNodes = $scope.allNodes;
```

**Comment by tonyGitHubRunoob** [comment]
i have same issue, who can help me?, i'm a noob.

**Comment by tonyGitHubRunoob** [comment]
i solved.as blow:
vm.allNodes = [];
		    vm.addToAllNodes = function(children) {
		        if (!children || typeof (children) == "array" && children.length == 0) {
		            return;
		        }      
		        for (var i = 0; i < children.length; i++) {
		        	if(children[i].children.length > 0){
		        		vm.allNodes.push(children[i]);
		        		vm.addToAllNodes(children[i].children); // 递归
		        	}
		        }
		    }

			vm.addToAllNodes(vm.dataForTheTree);
			vm.expandedNodes = vm.allNodes;

**Comment by jasmeetdd** [comment]
Though there should have been a simpler way of doing this (expanding or collapsing all nodes).
But thanks this saved hours of meaningless search.
The plugin is still awesomely fast for a large tree though.
