### ISSUE TITLE
allow for changing angular tag, '{{", to user-defined tag

### ISSUE THREAD

**Issue by namwkim** [wix/angular-tree-control#177]
It would be nice to allow for changing angular tag, '{{", to user-defined tag. Currently, user-defined tag is not supported. In many template engines such as Jinja2, template tags conflict with angular's tag.

**Comment by yoavaa** [comment]
1. why is that a problem? the {{ is contained inside the private template of the component
2. you can use a custom template for the component and configure it / angular as you like
