### ISSUE TITLE
order-by is not reacting to updates

### ISSUE THREAD

**Issue by bastrapp** [wix/angular-tree-control#178]
The order-by directive processes correctly the initial value but any update is ignored.

Here is a plunkr to show the behaviour. 
http://plnkr.co/edit/pMjZHJ4NOKsFt0Ls9nDO?p=preview
If you change the order-by value from 'name' to 'age' you will see no difference in the ordering of the tree. However, if you change app.js line 17 directly, the new order is used (but also cannot be changed).

**Comment by yoavaa** [comment]
fixed in latest version
