### ISSUE TITLE
Angular recursion errors in angular.copy with large data (several thousands)

### ISSUE THREAD

**Issue by bharatn** [wix/angular-tree-control#18]
The tree worked fine on smaller set of data

I am also using underscore, using underscore solved the issue
```
a = _.clone(a); a[$scope.options.nodeChildren] = [];
b = _.clone(b); b[$scope.options.nodeChildren] = [];
```

btw its nice and fast compared to treeview so thanks

**Comment by yoavaa** [comment]
just improved the tree performance and replaced copy with shallowCopy. that should solve your issue
