### ISSUE TITLE
Order by custom function

### ISSUE THREAD

**Issue by shaie** [wix/angular-tree-control#180]
I want to order the tree nodes by a custom function which places all "folder" before "files" and within each sorts by the node's "name". Reading the documentation, order-by is said to match what Angular's orderBy expects, and according to Angular I can either define a custom function, or pass an array of predicates, so that the elements are sorted by the first predicate, and in case of tie, by the second.

So I defined an `isFolder` function on my scope, which returns true if the node has any children, and false otherwise. If I use it in a custom HTML snippet, it works, as follows:

```
<ul>
  <li ng-repeat="node in treedata | orderBy: [isFolder, name]">
    {{node.name}}
  </li>
</ul>
```

The nodes are sorted as I want: folders before files, and within each by name.

However, trying to do that with the `treecontrol`, it doesn't work as `isFolder` is never called. This is how I defined it:

```
<treecontrol class="tree-classic"
             tree-model="treedata"
             options="treeOptions"
             on-selection="showSelected(node)"
             order-by="[isFolder, name]"
             reverse-order="false"
             selected-node="node1">
```

Digging in `angular-tree-control.js` I found that "order-by" is bound to the scope with '@', which copies the value (`[isFolder, name]`), however `isFolder` does not exist on the directive's scope. This is partially annoying, and I hope you could either document that, or improve the directive. But for now I found a work around. I noticed that the directive's scope references scope.$parent via `scope.parentScopeOfTree`, so I changed "order-by" to be `order-by="[parentScopeOfTree.isFolder, name]"`.

That still didn't work, as my `isFolder` was never called. After some trial and error, I found that making this change to angular-tree-control.js solves the problem:

```
var templateOptions = {
    orderBy: $scope.orderBy ? " | orderBy:" + $scope.orderBy + ":isReverse()" : '',
    ...
```

The previous line was

```
var templateOptions = {
    orderBy: $scope.orderBy ? " | orderBy:orderByFunc():isReverse()" : '',
```

Where `orderByFunc()` is a method which returns `"'" + $scope.orderBy + "'"`, and after adding console.log() prints to it, I saw that it does return the expression that I set ("[isFolder, name]"). However, for some reason isFolder wasn't called, where if I made the change that I propose, it does.

I am not sure why this happens, and I wasn't able to make it work without the change above. However, I noticed that with the change above, defining order-by as `order-by="name"` no longer works, so ... I'm now even more puzzled.

I'm relatively new to Angular, and I thought that I understand how scopes work, and I even wrote a couple of directives with isolated scopes, but I guess the treecontrol is more complex than what I did :).

I hope that you can either propose a work around without modifying angular-tree-control.js, or somehow fix it in the tree directive itself.

**Comment by yoavaa** [comment]
now supported just like ng-repeat. see at http://localhost:63342/angular.treecontrol/index.html#sorting

**Comment by shaie** [comment]
Thanks! BTW, you might want to update the link above to not point to localhost:63342 :)
