### ISSUE TITLE
Access to the parent of the parent node

### ISSUE THREAD

**Issue by shailjag** [wix/angular-tree-control#193]
how can we access to the parent of the parentNode

**Comment by jesusp** [comment]
I have the same question...

**Comment by yoavaa** [comment]
this is a duplicate issue - but I'll answer it here as well.

1. you cannot at this time
2. computing the array of parents is a bit complex and will impose a performance penalty if we do it and provide it like we provide $parentNode.
3. given we can only do it lazily, how would you imaging the syntax? 

as a function?
```
$parents() -> returns the array of parent nodes, starting with the current node?
```

maybe a better name is $path() ?

**Comment by yoavaa** [comment]
done. see the $path function  - 
http://wix.github.io/angular-tree-control/#events
and
http://wix.github.io/angular-tree-control/#labels-template
