### ISSUE TITLE
How to expand folder while maintaining "dirSelectable: true"

### ISSUE THREAD

**Issue by philipgriffin** [wix/angular-tree-control#199]
Hi,

I'm trying to expand a folder when the folder name is clicked but maintain `dirSelectable: true` so that I can use the node of the clicked folder.

Setting dirSelectable to false expands the folder but then the node is not accessible.

Is this possible?

**Comment by yoavaa** [comment]
set dirSelectable to true.

have an onSelection event handler, and in the event handler push the node (if it is a directory) to expandedNodes. This way, it will be both selected and expanded.

**Comment by philipgriffin** [comment]
Thanks
