### ISSUE TITLE
$scope.selected apply on children

### ISSUE THREAD

**Issue by inquota** [wix/angular-tree-control#212]
I have this $scope.selected = array[2]; to select a Node. When I choose $scope.selected = array[10] for example it doesn't select the Node which is a child.

**Comment by yoavaa** [comment]
can you provide more information? What you are doing should work, without a running example (or at least the code) I cannot help

**Comment by inquota** [comment]
Hi yoavaa, thanks for your response. I have another solution for this issue. Can be closed :).
