### ISSUE TITLE
Lazy Load Asynchronously?

### ISSUE THREAD

**Issue by esinek** [wix/angular-tree-control#213]
Is there a mechanism to load the data async where the data contains something like "hasChildren" or "childCount" so we can set the appropriate icon (turndown or leaf icon), and then if the user expands that node, we get the next level async (send expanded node id)?

**Comment by yoavaa** [comment]
you can do that using the isLeaf function
http://wix.github.io/angular-tree-control/#isleaf

**Comment by tyru** [comment]
I also tried lazy load using `isLeaf` and `on-node-toggle`.
https://gist.github.com/tyru/96a6afd47314f271c4b8695e1419c698

P.S. Thanks for inventing a great component :)
