### ISSUE TITLE
Check the license

### ISSUE THREAD

**Issue by pvnr0082t** [wix/angular-tree-control#216]
Hi @yoavaa ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team, we want to host this library on cdnjs.
We found that the [License](https://github.com/wix/angular-tree-control/blob/master/LICENSE) shows ```MIT```, but the license on [npm](https://www.npmjs.com/package/angular-tree-control) and [package.json](https://github.com/wix/angular-tree-control/blob/master/package.json) show ```ISC```.
Could you ckeck the licence you use for this repo?

https://github.com/cdnjs/cdnjs/pull/7811
https://github.com/cdnjs/cdnjs/issues/7470

**Comment by yoavaa** [comment]
The license is MIT, ISC was a mistake in package.json.
Now fixed. Thanks for finding this out.

**Comment by pvnr0082t** [comment]
Okay, Thanks for your help. :+1:
