### ISSUE TITLE
About latest released

### ISSUE THREAD

**Issue by pvnr0082t** [wix/angular-tree-control#218]
Hi @yoavaa ,
You just released __0.2.26__. Could you please publish the latest version on npm. Thanks.

https://github.com/cdnjs/cdnjs/pull/7811
https://github.com/cdnjs/cdnjs/issues/7470

**Comment by yoavaa** [comment]
I did. 
something strange going on with NPM - 

The banner NPM says 0.2.26
The version on the right says 0.2.25
![image](https://cloud.githubusercontent.com/assets/1107239/15096830/9941cf38-1511-11e6-8472-12f145aae867.png)

**Comment by yoavaa** [comment]
and NPM install brings 0.2.26

**Comment by pvnr0082t** [comment]
Oh!! It's true. Thanks for your help.
