### ISSUE TITLE
collisions with folder of same name

### ISSUE THREAD

**Issue by leggebroten** [wix/angular-tree-control#226]
Hi, 

I've attached a link to video demonstrating the issue.

Namely, when clicking on a folder name, the same name at the root level is also selected.
Double clicking the nested folder merely selects the one at the root (doesn't open the nested folder).

Thoughts?

http://screencast.com/t/v9b7TWVZ3Dyy

**Comment by yoavaa** [comment]
http://wix.github.io/angular-tree-control/#equality
I guess your two nodes appear equal for the default equality function of the tree.

**Comment by ewosleger** [comment]
I have having the same issue with the component. If a two parent nodes have same named child nodes, the first parent is traversed visual, however if selected they return correct node information. Any progress w/ this bug?

**Comment by yoavaa** [comment]
The solution is the same - using a custom equality function.
