### ISSUE TITLE
Option to expand all tree nodes

### ISSUE THREAD

**Issue by kvpt** [wix/angular-tree-control#25]
I know there is an option to do that #14, but it's require to provide all nodes to be expanded. But if you want to expand all nodes it's not convenient.

I have an api which return data in the right form _node, children[..]_ and it's redundant to have to extract all nodes.

An option should be added to expand all nodes if defaultExpanded array is empty **or** a wildcard **'*'** should be handled by defaultExpanded.

**Comment by asafebgi** [comment]
What would be nice is a routine that'll automatically expand all expandable nodes. For dynamic trees where the index of expandable nodes is unknown.
