### ISSUE TITLE
Remove overall padding

### ISSUE THREAD

**Issue by ChaudhryAtif** [wix/angular-tree-control#266]
I want to remove the padding on the left:

[![enter image description here][1]][1]

and have it like so:

[![enter image description here][2]][2]

But when I try to apply the following :

    [treecontrol] li {
        padding: 0;
    }

It sets the padding of the children to 0px too:

[![enter image description here][3]][3]

Is it possible to achieve desired result?

  [1]: https://i.stack.imgur.com/UPToo.png
  [2]: https://i.stack.imgur.com/r044m.png
  [3]: https://i.stack.imgur.com/G6jSN.png

**Comment by ChaudhryAtif** [comment]
```
[treecontrol] > ul > li {
    padding: 0;
}
```

[SO question](http://stackoverflow.com/a/41867386/4669619)

**Comment by yoavaa** [comment]
Just do 
treecontrol treeitem li {
    padding-left: 20px;
}
treecontrol li {
    padding: 0;
}
