### ISSUE TITLE
Access to the properties of the parent node

### ISSUE THREAD

**Issue by varuag** [wix/angular-tree-control#30]
The label of my nodes depend upon a property of their parent node and also, the index of the child node within the children array. Is there a way to access these? 

I've tried a number of angular based tree views, and this looks by far the most feature complete, with almost everything I need apart from the above.

**Comment by shailjag** [comment]
i need to select parent and its grand parent. can u please help??

**Comment by yoavaa** [comment]
The best option is to have a back reference in your node objects.
We had a long discussion about this, and there is no simple way to provide
such an API.
It will either be a function or an array with performance impact...
