### ISSUE TITLE
Dynamically append and remove a node.

### ISSUE THREAD

**Issue by abdulgaffar** [wix/angular-tree-control#42]
I want to append and remove a node to tree.

**Comment by buob** [comment]
Is there an approach you had in mind for removing a node?  The only way I can think of removing a node (from the actual node itself, i.e. a delete button on the node itself) out of the box is emit an event with the node to the containing controller and then walk the tree data and remove it from there.  It seems less than ideal, is there another mechanism that would allow that kind of thing?

**Comment by yoavaa** [comment]
what would you imagine the tree doing?

**Comment by buob** [comment]
I didn't know if there was something in place for a node to have knowledge of its parent so it could send the parent with the event and the directive could remove the node from the parent's children, or if there was an event already that a node could fire to its parent to remove itself.  If either of those options sound interesting, I could submit a PR.

**Comment by sethkrasnianski** [comment]
Any insight into this @yoavaa? I'm interested in doing the same thing that @buob is describing. I have a button next to each node which intends to remove said node from the tree, but to actually repaint the tree requires somehow walking the `treeModel` to find this node and removing it. Unless of course we're exposed the path to the current node somehow. It seems like there could / should be an easier way to do this.

**Comment by yoavaa** [comment]
in another issue we have a discussion on getting, for a node, the path of parents to the root (or rather, the path to a node). While this is possible, it is not trivial and I am not sure about the API. It has to be a function that we can expose similar to the other tree label template variables (e.g. http://wix.github.io/angular-tree-control/#labels-template and http://wix.github.io/angular-tree-control/#events). 

Do you think adding a ```$parents``` which is a function returning an array of nodes will help?

**Comment by paambaati** [comment]
@yoavaa That should definitely help. I too have a usecase that requires deleting nodes!

**Comment by paambaati** [comment]
@buob @sethkrasnianski Did you guys manage to find a workaround for this?

**Comment by yoavaa** [comment]
@paambaati what is the usecase?

If it is that when a node is clicked you want to remove it, you can use the $parentNode parameter you get in events. With it you can get the parent node of the clicked node and remove it from the parent.

**Comment by buob** [comment]
I think we were using a version before `$parentNode` was available, so we ended up just storing `parentNode` on each node ourselves before sending it to tree control and removing it that way.

**Comment by dkruep** [comment]
I am updating my treeModel by splicing children OUT of the structure. Although the tree model updates as expected, the tree's transcludeScope goes out of synch with the new data structure.

The result is that the tree's label continues to display the removed node's data even while the scope's node property is properly updated.

Am I missing something necessary in order to successfully remove nodes?

**Comment by dkruep** [comment]
Just an update to my prior question:

I discovered transcludeScopes for removed nodes remain synchronized with treeModel updates whenever NOT using the custom template option.
