### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by zhouwen0000** [wix/angular-tree-control#81]
"RangeError: Maximum call stack size exceeded" how do it?

**Comment by yoavaa** [comment]
probably an issue with the node copy and a large tree. I have changed the copy to shallow copy, so please try now with the new tree version

**Comment by sogndesign** [comment]
I got this error on code downloaded on 2/20/2015.

I got past it by writing my own equality routiine

**Comment by yoavaa** [comment]
today, with the fix in the equality method (last version), it should not
happen. Can you please try again?

**Comment by Wesseldr** [comment]
I'm hitting the same bug on version 0.2.23  on the search box if i type any thing working with angular 1.4.10

**Comment by yoavaa** [comment]
Can you share more information? What model are u using? What search box?

**Comment by denkan** [comment]
I'm facing the same error @ 0.2.28.

Seems to happen whenever the model gets rewritten with more or less items in the tree. Meaning:

- Case A) Retrieved new tree-model data with an **item changed property** `name` = no problem.
- Case B) Retrieved new tree-model data with an **item moved** from one item to another (switched parent) = no problem.
- Case C) = Retrieved new tree-model data with an **new item** somewhere in the tree = `Maximum call stack size exceeded` 
- Case D) = Retrieved new tree-model data with an **removed item** somewhere in the tree = `Maximum call stack size exceeded` 

All errors points to Angular's `equal()` function.

It does work if I reset the tree-model (`myTreeData =  []`) before loading new data to it.

**Comment by CodestarGames** [comment]
I've just started getting this same error as well with the latest version from the repository. All errors are pointing to Angular's equal() function like denkan said.

**Comment by yoavaa** [comment]
Donald, we have set a fix for this issue a while back. Can you share
exactly your setup that causes this problem?

**Comment by yhc1990518** [comment]
Hi, I have the same issue with 0.2.30, angular version is 1.6.4
