### ISSUE TITLE
node.$parentNode always coming null.

### ISSUE THREAD

**Issue by muralinit** [wix/angular-tree-control#83]
Whenever a node is selected I want to do some work with it's parent. So in my code to get the parent node as per the documentation I am calling node.$parentNode, but I am getting the value as undefined.

please refer the jsFiddle: http://jsfiddle.net/muralinit/a83ckpr4/7/. When I select a node it's parent is always coming as null. Please help in fixing this issue.

**Comment by yoavaa** [comment]
Yep. there is a bug there. Will work on fixing it

**Comment by muralinit** [comment]
Thank you very much for the quick response. I will be waiting for the fix.

**Comment by muralinit** [comment]
Hi Yoavaa,

Can you please let me know when this issue is going to be fixed.

Thanks & Regards,
N.Murali Krishna.

**Comment by ibha** [comment]
Hi Yoavaa, I also need this fix. Please let me know when you are planning to fix it.
Thanks

**Comment by yoavaa** [comment]
Try $nodeParent, not node.$nodeParent

**Comment by ibha** [comment]
Thanks for the quick reply. This is how I tried:
on-selection="showSelected($nodeParent, node, selected)"

  $scope.showSelected = function($nodeParent, node, selected) {
console.log($nodeParent);
            };

Also tried $parentNode instead of $nodeParent but same results.
It prints undefined. Please advise

**Comment by yoavaa** [comment]
ha...
$parentNode is only supported in the label template, not in the
on-selection callback.
Did not think of this use case....

can think of how to implement this... if it is critical..

**Comment by ibha** [comment]
It’ll be helpful to get this, otherwise I have to make extra api calls just to get this.
You are right $parentNode works with label.
Thanks

**Comment by muralinit** [comment]
Hi Yovva,

Was this issue is going to take some more time to fix?
Because this feature became critical to me now. Please let me know, if it is not possible to fix I will look for some alternate solution.

Thanks & Regards,
N.Murali Krishna.

**Comment by brianfeister** [comment]
:+1: Need access to this in `on-node-toggle`, I realize the use case is different than `on-selection`.

**Comment by muralinit** [comment]
Hi Yovva,

It's already 7 months over after logging this issue. Can you please put your focus on this issue, because most of the people are waiting for this feature.

If you solve this problem it will be helpful to so many people. We thought of over coming this problem using Defiant.js but in that library also they are not supporting the retrieval of parent functionality.

Thanks & Regards,
N.Murali Krishna.

**Comment by yoavaa** [comment]
ok, this was a new requirement, a bit complex, but finally it is here
http://wix.github.io/angular-tree-control/#events

Enjoy
