### ISSUE TITLE
Not allow the node to be unselected

### ISSUE THREAD

**Issue by softengi** [wix/angular-tree-control#86]
I need a node in the tree to remain selected till the user selects another node. I do understand that this behavior was updated as part of another change made - https://github.com/wix/angular-tree-control/issues/40

Could the original behavior be made available by some configurable option?

Thanks.

**Comment by PeterClough** [comment]
I need this too please the deselect on second click makes no sense in my project.

Thanks

**Comment by sansjunk** [comment]
+1 for this feature

**Comment by atilapoltronieri** [comment]
There is an way to do that, or not to:

$scope.selectNodeLaber = function (selectedNode { 
...
}

In this function look for the "$scope.selectedNode = undefined;" and comment this line. 
Note: Do this if you don't want to unselect all yours trees, my case.

**Comment by tomasbeke** [comment]
There's a pending pull request for this feature: https://github.com/wix/angular-tree-control/pull/127

**Comment by alinnert** [comment]
I think this issue can be closed, right?

~~~javascript
$scope.treeOptions = {
    allowDeselect: false
};
~~~

This works as expected.

**Comment by tomasbeke** [comment]
I think so. Thanks!

**Comment by softengi** [comment]
Yup. What @alinnert suggested works. Thanks.
