### ISSUE TITLE
Disable node selection

### ISSUE THREAD

**Issue by santhoshmeti** [wix/angular-tree-control#88]
I am new to this angular-tree view. I want to know is there any way that i can disable node from being selected.

**Comment by mruzekw** [comment]
I've been looking for this feature as well.

**Comment by techniq** [comment]
I would also like this functionality

**Comment by techniq** [comment]
See my [PR](https://github.com/wix/angular-tree-control/pull/140) and associated [issue](https://github.com/wix/angular-tree-control/issues/137)
