### ISSUE TITLE
How do i pre select a child node ?

### ISSUE THREAD

**Issue by Goochie** [wix/angular-tree-control#90]
I know that by using selected-node="selectedNode" you can select specific node, but this seems problematic for selecting child node as you end up with something like ..

selectedNode[0].children[2]

My question is how do you get a reference to a selected child node as the node object on selection only return the object ..

on-selection="deskSelected(node)"

**Comment by yoavaa** [comment]
don't understand what you expect. You have control over the expanded and selected nodes both via binding and events. What more can the tree do?

**Comment by dsmithco** [comment]
Can the original request here be revisited? Basically if a child is selected then auto expand it's parents. This is helpful if there are several levels.
