### ISSUE TITLE
Performance on a 13,000+ node tree

### ISSUE THREAD

**Issue by zavierrodriguez** [wix/angular-tree-control#95]
I'm trying out your grid and getting pretty poor performance (6 seconds to expand root node) on a tree of this size (13,000+ nodes).  Is this expected or have I configured something incorrectly?

**Comment by yoavaa** [comment]
please try with the new version of the tree - it should have better performance. 
if that does not work, please share a reproducible example.

**Comment by evilaliv3** [comment]
@yoavaa on [GlobaLeaks](https://github.com/globaleaks/GlobaLeaks) we are evaluating the use of angular-tree-control inside our form builder to make possible for a user to select options from a hierarchic select-box like the one implemented by angular-tree-control (https://github.com/globaleaks/GlobaLeaks/issues/1408).

we would have the need to deal with long lists (not +13.000) and i'm wondering how this would impact not only from a performance point of view but mostly from the user experience point of view;
suppose infact that one loads a veri long list and has to scroll down a lot to find the element he would like to click. have you ever dealt with such a requirement and what would be your suggestion?

**Comment by yoavaa** [comment]
I have not dealt with such large trees. We had a few people talking about
such trees and trying to implement different patches to support them - but
unless you try you will not know if the tree supports you specific use case

On Wed, Sep 9, 2015 at 2:10 PM, Giovanni Pellerano <notifications@github.com

**Comment by zavierrodriguez** [comment]
I originally posed this question and indeed, Yoav's suggestion to try the later version of the tree at that time did increase the performance immensely.  The performance was sub-second on 13,000+ node tree opening a deeply nested node dynamically.  Thanks for a great update!
